# Generated by Django 4.1 on 2022-09-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produced_energy_in_wh', models.FloatField()),
                ('consumed_energy_in_wh', models.FloatField()),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
