# Generated by Django 4.1 on 2022-09-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeterReading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='transaction_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
